/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as WalletAddressRouteImport } from './routes/wallet-address'
import { Route as TeamRouteImport } from './routes/team'
import { Route as RobotRouteImport } from './routes/robot'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RechargeRouteImport } from './routes/recharge'
import { Route as ProfitRouteImport } from './routes/profit'
import { Route as PersonalInfoRouteImport } from './routes/personal-info'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as JobRouteImport } from './routes/job'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FundPasswordRouteImport } from './routes/fund-password'
import { Route as CompanyProfileRouteImport } from './routes/company-profile'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Kasongo1IndexRouteImport } from './routes/kasongo1.index'
import { Route as Kasongo1WithdrawalsRouteImport } from './routes/kasongo1.withdrawals'
import { Route as Kasongo1UsersRouteImport } from './routes/kasongo1.users'
import { Route as Kasongo1SettingsRouteImport } from './routes/kasongo1.settings'
import { Route as Kasongo1LoginRouteImport } from './routes/kasongo1.login'
import { Route as Kasongo1DepositsRouteImport } from './routes/kasongo1.deposits'
import { Route as Kasongo1DashboardRouteImport } from './routes/kasongo1.dashboard'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletAddressRoute = WalletAddressRouteImport.update({
  id: '/wallet-address',
  path: '/wallet-address',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotRoute = RobotRouteImport.update({
  id: '/robot',
  path: '/robot',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeRoute = RechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitRoute = ProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalInfoRoute = PersonalInfoRouteImport.update({
  id: '/personal-info',
  path: '/personal-info',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const JobRoute = JobRouteImport.update({
  id: '/job',
  path: '/job',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FundPasswordRoute = FundPasswordRouteImport.update({
  id: '/fund-password',
  path: '/fund-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyProfileRoute = CompanyProfileRouteImport.update({
  id: '/company-profile',
  path: '/company-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Kasongo1IndexRoute = Kasongo1IndexRouteImport.update({
  id: '/kasongo1/',
  path: '/kasongo1/',
  getParentRoute: () => rootRouteImport,
} as any)
const Kasongo1WithdrawalsRoute = Kasongo1WithdrawalsRouteImport.update({
  id: '/kasongo1/withdrawals',
  path: '/kasongo1/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const Kasongo1UsersRoute = Kasongo1UsersRouteImport.update({
  id: '/kasongo1/users',
  path: '/kasongo1/users',
  getParentRoute: () => rootRouteImport,
} as any)
const Kasongo1SettingsRoute = Kasongo1SettingsRouteImport.update({
  id: '/kasongo1/settings',
  path: '/kasongo1/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const Kasongo1LoginRoute = Kasongo1LoginRouteImport.update({
  id: '/kasongo1/login',
  path: '/kasongo1/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Kasongo1DepositsRoute = Kasongo1DepositsRouteImport.update({
  id: '/kasongo1/deposits',
  path: '/kasongo1/deposits',
  getParentRoute: () => rootRouteImport,
} as any)
const Kasongo1DashboardRoute = Kasongo1DashboardRouteImport.update({
  id: '/kasongo1/dashboard',
  path: '/kasongo1/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/company-profile': typeof CompanyProfileRoute
  '/fund-password': typeof FundPasswordRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/invite': typeof InviteRoute
  '/job': typeof JobRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/personal-info': typeof PersonalInfoRoute
  '/profit': typeof ProfitRoute
  '/recharge': typeof RechargeRoute
  '/register': typeof RegisterRoute
  '/robot': typeof RobotRoute
  '/team': typeof TeamRoute
  '/wallet-address': typeof WalletAddressRoute
  '/withdraw': typeof WithdrawRoute
  '/kasongo1/dashboard': typeof Kasongo1DashboardRoute
  '/kasongo1/deposits': typeof Kasongo1DepositsRoute
  '/kasongo1/login': typeof Kasongo1LoginRoute
  '/kasongo1/settings': typeof Kasongo1SettingsRoute
  '/kasongo1/users': typeof Kasongo1UsersRoute
  '/kasongo1/withdrawals': typeof Kasongo1WithdrawalsRoute
  '/kasongo1/': typeof Kasongo1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/company-profile': typeof CompanyProfileRoute
  '/fund-password': typeof FundPasswordRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/invite': typeof InviteRoute
  '/job': typeof JobRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/personal-info': typeof PersonalInfoRoute
  '/profit': typeof ProfitRoute
  '/recharge': typeof RechargeRoute
  '/register': typeof RegisterRoute
  '/robot': typeof RobotRoute
  '/team': typeof TeamRoute
  '/wallet-address': typeof WalletAddressRoute
  '/withdraw': typeof WithdrawRoute
  '/kasongo1/dashboard': typeof Kasongo1DashboardRoute
  '/kasongo1/deposits': typeof Kasongo1DepositsRoute
  '/kasongo1/login': typeof Kasongo1LoginRoute
  '/kasongo1/settings': typeof Kasongo1SettingsRoute
  '/kasongo1/users': typeof Kasongo1UsersRoute
  '/kasongo1/withdrawals': typeof Kasongo1WithdrawalsRoute
  '/kasongo1': typeof Kasongo1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/company-profile': typeof CompanyProfileRoute
  '/fund-password': typeof FundPasswordRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/invite': typeof InviteRoute
  '/job': typeof JobRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/personal-info': typeof PersonalInfoRoute
  '/profit': typeof ProfitRoute
  '/recharge': typeof RechargeRoute
  '/register': typeof RegisterRoute
  '/robot': typeof RobotRoute
  '/team': typeof TeamRoute
  '/wallet-address': typeof WalletAddressRoute
  '/withdraw': typeof WithdrawRoute
  '/kasongo1/dashboard': typeof Kasongo1DashboardRoute
  '/kasongo1/deposits': typeof Kasongo1DepositsRoute
  '/kasongo1/login': typeof Kasongo1LoginRoute
  '/kasongo1/settings': typeof Kasongo1SettingsRoute
  '/kasongo1/users': typeof Kasongo1UsersRoute
  '/kasongo1/withdrawals': typeof Kasongo1WithdrawalsRoute
  '/kasongo1/': typeof Kasongo1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/company-profile'
    | '/fund-password'
    | '/history'
    | '/home'
    | '/invite'
    | '/job'
    | '/join'
    | '/login'
    | '/personal-info'
    | '/profit'
    | '/recharge'
    | '/register'
    | '/robot'
    | '/team'
    | '/wallet-address'
    | '/withdraw'
    | '/kasongo1/dashboard'
    | '/kasongo1/deposits'
    | '/kasongo1/login'
    | '/kasongo1/settings'
    | '/kasongo1/users'
    | '/kasongo1/withdrawals'
    | '/kasongo1/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/company-profile'
    | '/fund-password'
    | '/history'
    | '/home'
    | '/invite'
    | '/job'
    | '/join'
    | '/login'
    | '/personal-info'
    | '/profit'
    | '/recharge'
    | '/register'
    | '/robot'
    | '/team'
    | '/wallet-address'
    | '/withdraw'
    | '/kasongo1/dashboard'
    | '/kasongo1/deposits'
    | '/kasongo1/login'
    | '/kasongo1/settings'
    | '/kasongo1/users'
    | '/kasongo1/withdrawals'
    | '/kasongo1'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/company-profile'
    | '/fund-password'
    | '/history'
    | '/home'
    | '/invite'
    | '/job'
    | '/join'
    | '/login'
    | '/personal-info'
    | '/profit'
    | '/recharge'
    | '/register'
    | '/robot'
    | '/team'
    | '/wallet-address'
    | '/withdraw'
    | '/kasongo1/dashboard'
    | '/kasongo1/deposits'
    | '/kasongo1/login'
    | '/kasongo1/settings'
    | '/kasongo1/users'
    | '/kasongo1/withdrawals'
    | '/kasongo1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CompanyProfileRoute: typeof CompanyProfileRoute
  FundPasswordRoute: typeof FundPasswordRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  InviteRoute: typeof InviteRoute
  JobRoute: typeof JobRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  PersonalInfoRoute: typeof PersonalInfoRoute
  ProfitRoute: typeof ProfitRoute
  RechargeRoute: typeof RechargeRoute
  RegisterRoute: typeof RegisterRoute
  RobotRoute: typeof RobotRoute
  TeamRoute: typeof TeamRoute
  WalletAddressRoute: typeof WalletAddressRoute
  WithdrawRoute: typeof WithdrawRoute
  Kasongo1DashboardRoute: typeof Kasongo1DashboardRoute
  Kasongo1DepositsRoute: typeof Kasongo1DepositsRoute
  Kasongo1LoginRoute: typeof Kasongo1LoginRoute
  Kasongo1SettingsRoute: typeof Kasongo1SettingsRoute
  Kasongo1UsersRoute: typeof Kasongo1UsersRoute
  Kasongo1WithdrawalsRoute: typeof Kasongo1WithdrawalsRoute
  Kasongo1IndexRoute: typeof Kasongo1IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet-address': {
      id: '/wallet-address'
      path: '/wallet-address'
      fullPath: '/wallet-address'
      preLoaderRoute: typeof WalletAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robot': {
      id: '/robot'
      path: '/robot'
      fullPath: '/robot'
      preLoaderRoute: typeof RobotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge': {
      id: '/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof RechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit': {
      id: '/profit'
      path: '/profit'
      fullPath: '/profit'
      preLoaderRoute: typeof ProfitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-info': {
      id: '/personal-info'
      path: '/personal-info'
      fullPath: '/personal-info'
      preLoaderRoute: typeof PersonalInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job': {
      id: '/job'
      path: '/job'
      fullPath: '/job'
      preLoaderRoute: typeof JobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund-password': {
      id: '/fund-password'
      path: '/fund-password'
      fullPath: '/fund-password'
      preLoaderRoute: typeof FundPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-profile': {
      id: '/company-profile'
      path: '/company-profile'
      fullPath: '/company-profile'
      preLoaderRoute: typeof CompanyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasongo1/': {
      id: '/kasongo1/'
      path: '/kasongo1'
      fullPath: '/kasongo1/'
      preLoaderRoute: typeof Kasongo1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasongo1/withdrawals': {
      id: '/kasongo1/withdrawals'
      path: '/kasongo1/withdrawals'
      fullPath: '/kasongo1/withdrawals'
      preLoaderRoute: typeof Kasongo1WithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasongo1/users': {
      id: '/kasongo1/users'
      path: '/kasongo1/users'
      fullPath: '/kasongo1/users'
      preLoaderRoute: typeof Kasongo1UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasongo1/settings': {
      id: '/kasongo1/settings'
      path: '/kasongo1/settings'
      fullPath: '/kasongo1/settings'
      preLoaderRoute: typeof Kasongo1SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasongo1/login': {
      id: '/kasongo1/login'
      path: '/kasongo1/login'
      fullPath: '/kasongo1/login'
      preLoaderRoute: typeof Kasongo1LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasongo1/deposits': {
      id: '/kasongo1/deposits'
      path: '/kasongo1/deposits'
      fullPath: '/kasongo1/deposits'
      preLoaderRoute: typeof Kasongo1DepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasongo1/dashboard': {
      id: '/kasongo1/dashboard'
      path: '/kasongo1/dashboard'
      fullPath: '/kasongo1/dashboard'
      preLoaderRoute: typeof Kasongo1DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CompanyProfileRoute: CompanyProfileRoute,
  FundPasswordRoute: FundPasswordRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  InviteRoute: InviteRoute,
  JobRoute: JobRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  PersonalInfoRoute: PersonalInfoRoute,
  ProfitRoute: ProfitRoute,
  RechargeRoute: RechargeRoute,
  RegisterRoute: RegisterRoute,
  RobotRoute: RobotRoute,
  TeamRoute: TeamRoute,
  WalletAddressRoute: WalletAddressRoute,
  WithdrawRoute: WithdrawRoute,
  Kasongo1DashboardRoute: Kasongo1DashboardRoute,
  Kasongo1DepositsRoute: Kasongo1DepositsRoute,
  Kasongo1LoginRoute: Kasongo1LoginRoute,
  Kasongo1SettingsRoute: Kasongo1SettingsRoute,
  Kasongo1UsersRoute: Kasongo1UsersRoute,
  Kasongo1WithdrawalsRoute: Kasongo1WithdrawalsRoute,
  Kasongo1IndexRoute: Kasongo1IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
